//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// A high-level, AI-generated summary of an agreement document.
    /// </summary>
    public class AgreementSummary
    {

        /// <summary>
        /// An AI-generated summary of the agreement. This summary is provided for convenience <br/>
        /// 
        /// <remarks>
        /// and may not capture every detail of the original agreement.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("summary")]
        public string? Summary { get; set; }
    }
}