//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class CustomPropertyType
    {
        private CustomPropertyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static CustomPropertyType Str { get { return new CustomPropertyType("str"); } }
        
        public static CustomPropertyType Number { get { return new CustomPropertyType("number"); } }
        
        public static CustomPropertyType Boolean { get { return new CustomPropertyType("boolean"); } }
        
        public static CustomPropertyType MapOfAny { get { return new CustomPropertyType("mapOfAny"); } }
        
        public static CustomPropertyType ArrayOfAny { get { return new CustomPropertyType("arrayOfAny"); } }
        
        public static CustomPropertyType Null { get { return new CustomPropertyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CustomPropertyType v) { return v.Value; }
        public static CustomPropertyType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "mapOfAny": return MapOfAny;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for CustomPropertyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CustomPropertyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(CustomProperty.CustomPropertyConverter))]
    public class CustomProperty {
        public CustomProperty(CustomPropertyType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public CustomPropertyType Type { get; set; }


        public static CustomProperty CreateStr(string str) {
            CustomPropertyType typ = CustomPropertyType.Str;

            CustomProperty res = new CustomProperty(typ);
            res.Str = str;
            return res;
        }

        public static CustomProperty CreateNumber(double number) {
            CustomPropertyType typ = CustomPropertyType.Number;

            CustomProperty res = new CustomProperty(typ);
            res.Number = number;
            return res;
        }

        public static CustomProperty CreateBoolean(bool boolean) {
            CustomPropertyType typ = CustomPropertyType.Boolean;

            CustomProperty res = new CustomProperty(typ);
            res.Boolean = boolean;
            return res;
        }

        public static CustomProperty CreateMapOfAny(Dictionary<string, object> mapOfAny) {
            CustomPropertyType typ = CustomPropertyType.MapOfAny;

            CustomProperty res = new CustomProperty(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }

        public static CustomProperty CreateArrayOfAny(List<object> arrayOfAny) {
            CustomPropertyType typ = CustomPropertyType.ArrayOfAny;

            CustomProperty res = new CustomProperty(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static CustomProperty CreateNull() {
            CustomPropertyType typ = CustomPropertyType.Null;
            return new CustomProperty(typ);
        }

        public class CustomPropertyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(CustomProperty);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"'){
                    return new CustomProperty(CustomPropertyType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new CustomProperty(CustomPropertyType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new CustomProperty(CustomPropertyType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new CustomProperty(CustomPropertyType.MapOfAny)
                    {
                        MapOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, object>), new CustomProperty(CustomPropertyType.MapOfAny), "MapOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CustomProperty(CustomPropertyType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new CustomProperty(CustomPropertyType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                CustomProperty res = (CustomProperty)value;
                if (CustomPropertyType.FromString(res.Type).Equals(CustomPropertyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfAny));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}