//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of event that triggers the workflow. In this case, the workflow is initiated<br/>
    /// 
    /// <remarks>
    /// by an HTTP request. Future iterations may support additional event types beyond HTTP.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum TriggerEventType
    {
        [JsonProperty("HTTP")]
        Http,
    }

    public static class TriggerEventTypeExtension
    {
        public static string Value(this TriggerEventType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TriggerEventType ToEnum(this string value)
        {
            foreach(var field in typeof(TriggerEventType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TriggerEventType)
                    {
                        return (TriggerEventType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TriggerEventType");
        }
    }

}