//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class WorkflowInstanceCollection
    {

        /// <summary>
        /// Array of workflow instances
        /// </summary>
        [JsonProperty("data")]
        public List<WorkflowInstance>? Data { get; set; }

        /// <summary>
        /// Control information and metadata for the response.
        /// </summary>
        [JsonProperty("response_metadata")]
        public ResponseMetadata? ResponseMetadata { get; set; }
    }
}