//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Models.Errors;
    using Docusign.IAM.SDK.Utils;
    using System;

    public interface IConnectedFields
    {
        public ITabInfo TabInfo { get; }
    }

    public class ConnectedFields: IConnectedFields
    {
        public SDKConfig SDKConfiguration { get; private set; }
        private const string _language = "csharp";
        private const string _sdkVersion = "1.0.0-beta.2";
        private const string _sdkGenVersion = "2.638.5";
        private const string _openapiDocVersion = "v1";
        public ITabInfo TabInfo { get; private set; }

        public ConnectedFields(SDKConfig config)
        {
            SDKConfiguration = config;
            TabInfo = new TabInfo(SDKConfiguration);
        }
    }
}