//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Models.Errors;
    using Docusign.IAM.SDK.Utils;
    using System;

    public interface IMaestro
    {
        public IWorkflows Workflows { get; }

        public IWorkflowInstanceManagement WorkflowInstanceManagement { get; }
    }

    public class Maestro: IMaestro
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// Workflows SubSDK.
        /// <see cref="IWorkflows"/>
        /// </summary>
        public IWorkflows Workflows { get; private set; }

        /// <summary>
        /// WorkflowInstanceManagement SubSDK.
        /// <see cref="IWorkflowInstanceManagement"/>
        /// </summary>
        public IWorkflowInstanceManagement WorkflowInstanceManagement { get; private set; }

        public Maestro(SDKConfig config)
        {
            SDKConfiguration = config;
            Workflows = new Workflows(SDKConfiguration);
            WorkflowInstanceManagement = new WorkflowInstanceManagement(SDKConfiguration);
        }
    }
}