//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Models.Errors;
    using Docusign.IAM.SDK.Utils;
    using System;

    public interface IWorkspaces1
    {
        public IWorkspaceBrands WorkspaceBrands { get; }

        public IWorkspaceDocuments WorkspaceDocuments { get; }

        public IWorkspaceUploadRequest WorkspaceUploadRequest { get; }

        public IWorkspaceUsers WorkspaceUsers { get; }

        public IWorkspaces2 Workspaces { get; }
    }

    public class Workspaces1: IWorkspaces1
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// WorkspaceBrands SubSDK.
        /// <see cref="IWorkspaceBrands"/>
        /// </summary>
        public IWorkspaceBrands WorkspaceBrands { get; private set; }

        /// <summary>
        /// WorkspaceDocuments SubSDK.
        /// <see cref="IWorkspaceDocuments"/>
        /// </summary>
        public IWorkspaceDocuments WorkspaceDocuments { get; private set; }

        /// <summary>
        /// WorkspaceUploadRequest SubSDK.
        /// <see cref="IWorkspaceUploadRequest"/>
        /// </summary>
        public IWorkspaceUploadRequest WorkspaceUploadRequest { get; private set; }

        /// <summary>
        /// WorkspaceUsers SubSDK.
        /// <see cref="IWorkspaceUsers"/>
        /// </summary>
        public IWorkspaceUsers WorkspaceUsers { get; private set; }

        /// <summary>
        /// Workspaces SubSDK.
        /// <see cref="IWorkspaces2"/>
        /// </summary>
        public IWorkspaces2 Workspaces { get; private set; }

        public Workspaces1(SDKConfig config)
        {
            SDKConfiguration = config;
            WorkspaceBrands = new WorkspaceBrands(SDKConfiguration);
            WorkspaceDocuments = new WorkspaceDocuments(SDKConfiguration);
            WorkspaceUploadRequest = new WorkspaceUploadRequest(SDKConfiguration);
            WorkspaceUsers = new WorkspaceUsers(SDKConfiguration);
            Workspaces = new Workspaces2(SDKConfiguration);
        }
    }
}