//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Models.Errors;
    using Docusign.IAM.SDK.Utils;
    using System;

    public interface IWorkspaces1
    {
        public IWorkspaceBrands WorkspaceBrands { get; }
        public IWorkspaceDocuments WorkspaceDocuments { get; }
        public IWorkspaceUploadRequest WorkspaceUploadRequest { get; }
        public IWorkspaceUsers WorkspaceUsers { get; }
        public IWorkspaces2 Workspaces { get; }
    }

    public class Workspaces1: IWorkspaces1
    {
        public SDKConfig SDKConfiguration { get; private set; }
        private const string _language = "csharp";
        private const string _sdkVersion = "1.0.0-beta.6";
        private const string _sdkGenVersion = "2.727.4";
        private const string _openapiDocVersion = "v1";
        public IWorkspaceBrands WorkspaceBrands { get; private set; }
        public IWorkspaceDocuments WorkspaceDocuments { get; private set; }
        public IWorkspaceUploadRequest WorkspaceUploadRequest { get; private set; }
        public IWorkspaceUsers WorkspaceUsers { get; private set; }
        public IWorkspaces2 Workspaces { get; private set; }

        public Workspaces1(SDKConfig config)
        {
            SDKConfiguration = config;
            WorkspaceBrands = new WorkspaceBrands(SDKConfiguration);
            WorkspaceDocuments = new WorkspaceDocuments(SDKConfiguration);
            WorkspaceUploadRequest = new WorkspaceUploadRequest(SDKConfiguration);
            WorkspaceUsers = new WorkspaceUsers(SDKConfiguration);
            Workspaces = new Workspaces2(SDKConfiguration);
        }
    }
}