//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK
{
    using Docusign.IAM.SDK.Hooks;
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Models.Errors;
    using Docusign.IAM.SDK.Models.Requests;
    using Docusign.IAM.SDK.Utils;
    using Docusign.IAM.SDK.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading.Tasks;

    public interface IWorkflows
    {

        /// <summary>
        /// Retrieve a list of available Maestro workflows
        /// 
        /// <remarks>
        /// This operation retrieves a list of all available Maestro workflows. It returns basic information<br/>
        /// about each workflow, including its unique identifier (`id`), name, description, and the input<br/>
        /// schema required to trigger the workflow.<br/>
        /// <br/>
        /// The response provides key details that help users identify which workflows are available<br/>
        /// and understand the input requirements for triggering each one. Each workflow entry also includes<br/>
        /// metadata, such as when it was created, last modified, and by whom.<br/>
        /// <br/>
        /// This operation is useful for obtaining an overview of all workflows within the system, helping<br/>
        /// users and systems know what workflows are defined, what inputs they require, and how they can<br/>
        /// be triggered.<br/>
        /// <br/>
        /// ### Use Cases:<br/>
        /// - Listing all available workflows in a system for manual or automated workflow initiation.<br/>
        /// - Reviewing the input requirements for a workflow before triggering it programmatically.<br/>
        /// - Gathering basic metadata about workflows for auditing, logging, or reporting purposes.<br/>
        /// <br/>
        /// ### Key Features:<br/>
        /// - **Comprehensive Workflow Overview**: Provides a full list of workflows, giving visibility<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   into all the automated processes available within the Maestro platform.<br/>
        /// - **Input Schema Information**: Each workflow includes its trigger input schema, showing<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   what data must be provided when triggering the workflow.<br/>
        /// - **Metadata for Tracking**: Useful metadata like creation time, last modification date,<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   and user details are included to support tracking and auditing workflows.<br/>
        /// - **Future-Proof**: The operation is designed to be expandable as more workflows are added<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   or the platform grows, ensuring scalability in the workflow management process.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<WorkflowsListSuccess> GetWorkflowsListAsync(string accountId, Status? status = null, RetryConfig? retryConfig = null);

        /// <summary>
        /// Retrieve trigger requirements for a specific Maestro workflow
        /// 
        /// <remarks>
        /// This operation retrieves the configuration and input requirements necessary to trigger a specific<br/>
        /// Maestro workflow. It provides detailed information about the `trigger_event_type`, such as HTTP<br/>
        /// or other supported types, and specifies the required input schema, including field names, data types,<br/>
        /// and any default values.<br/>
        /// <br/>
        /// This information is essential for understanding the data and parameters required to initiate the<br/>
        /// workflow. It enables developers to prepare the necessary inputs and configuration before triggering<br/>
        /// the workflow instance, ensuring seamless execution and compliance with workflow requirements.<br/>
        /// <br/>
        /// ### Use Cases:<br/>
        /// - Identifying the required input fields and their data types to successfully trigger the workflow.<br/>
        /// - Reviewing the trigger configuration for validation and compliance with expected input.<br/>
        /// - Preparing and validating data in advance of triggering the workflow, minimizing runtime errors.<br/>
        /// <br/>
        /// ### Key Features:<br/>
        /// - **Detailed Trigger Input Requirements**: Provides an exhaustive schema of required fields,<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   their data types, and optional default values for easy reference and data validation.<br/>
        /// - **Trigger Event Type Information**: Specifies the type of event required to initiate the workflow<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   (e.g., HTTP), helping developers configure their systems to invoke the workflow appropriately.<br/>
        /// - **Configurable for Custom Triggers**: Suitable for custom configurations, enabling flexibility<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   in how workflows can be triggered according to system needs.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<WorkflowTriggerRequirementsSuccess> GetWorkflowTriggerRequirementsAsync(string accountId, string workflowId, RetryConfig? retryConfig = null);

        /// <summary>
        /// Trigger a new instance of a Maestro workflow
        /// 
        /// <remarks>
        /// This operation triggers a new instance of a specified Maestro workflow. When invoked,<br/>
        /// the workflow is started based on the provided input data, and the workflow instance<br/>
        /// begins executing according to its defined logic and configuration.<br/>
        /// <br/>
        /// The request requires an `instance_name` and any input data necessary to start the workflow,<br/>
        /// as described by the workflow&apos;s `trigger_input_schema`. The `instance_name` is a user-defined<br/>
        /// label for tracking the workflow run, while the input data fields should match the schema defined<br/>
        /// in the workflow.<br/>
        /// <br/>
        /// The operation is event-driven and typically triggered by an external HTTP event or system call,<br/>
        /// allowing for the automatic execution of complex processes that span multiple systems or components.<br/>
        /// <br/>
        /// Upon successful execution, the response returns the unique identifier (`id`) for the newly<br/>
        /// created workflow instance, along with a URL (`workflow_instance_url`) that can be used to<br/>
        /// interact with or track the running instance.<br/>
        /// <br/>
        /// ### Use Cases:<br/>
        /// - Automating user registration workflows where input fields like `name` and `email` are provided.<br/>
        /// - Processing financial transactions where details such as `amount` and `currency` are required.<br/>
        /// - Sending notifications based on user interactions in other systems.<br/>
        /// <br/>
        /// ### Key Features:<br/>
        /// - **Automated Execution**: Once triggered, the workflow runs until a step requires manual intervention.<br/>
        /// - **Input-Driven**: Workflow execution is based on the provided input data, which is validated<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   against the workflow&apos;s input schema.<br/>
        /// - **Real-Time Triggering**: Designed to be invoked as part of an event-driven architecture,<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   allowing for workflows to respond to external events.<br/>
        /// - **Tracking and Interaction**: The response includes a URL that allows users to check the status<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        ///   of the workflow instance or take further actions while it runs.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<TriggerWorkflowSuccess> TriggerWorkflowAsync(string accountId, string workflowId, TriggerWorkflow triggerWorkflow, RetryConfig? retryConfig = null);

        /// <summary>
        /// Pause an Active Workflow
        /// 
        /// <remarks>
        /// This operation pauses new workflow instances from being created. Any running workflows instances will be unaffected.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<PauseNewWorkflowInstancesSuccess> PauseNewWorkflowInstancesAsync(string accountId, string workflowId, RetryConfig? retryConfig = null);

        /// <summary>
        /// Resume a Paused Workflow
        /// 
        /// <remarks>
        /// This operation enables new workflow instances to be created<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<ResumeNewWorkflowInstancesSuccess> ResumePausedWorkflowAsync(string accountId, string workflowId, RetryConfig? retryConfig = null);
    }

    public class Workflows: IWorkflows
    {
        public SDKConfig SDKConfiguration { get; private set; }
        private const string _language = "csharp";
        private const string _sdkVersion = "1.0.0-beta.6";
        private const string _sdkGenVersion = "2.727.4";
        private const string _openapiDocVersion = "v1";

        public Workflows(SDKConfig config)
        {
            SDKConfiguration = config;
        }

        public async Task<WorkflowsListSuccess> GetWorkflowsListAsync(string accountId, Status? status = null, RetryConfig? retryConfig = null)
        {
            var request = new GetWorkflowsListRequest()
            {
                AccountId = accountId,
                Status = status,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/v1/accounts/{accountId}/workflows", request);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "GetWorkflowsList", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            if (retryConfig == null)
            {
                if (this.SDKConfiguration.RetryConfig != null)
                {
                    retryConfig = this.SDKConfiguration.RetryConfig;
                }
                else
                {
                    var backoff = new BackoffStrategy(
                        initialIntervalMs: 500L,
                        maxIntervalMs: 5000L,
                        maxElapsedTimeMs: 30000L,
                        exponent: 1.5
                    );
                    retryConfig = new RetryConfig(
                        strategy: RetryConfig.RetryStrategy.BACKOFF,
                        backoff: backoff,
                        retryConnectionErrors: true
                    );
                }
            }

            List<string> statusCodes = new List<string>
            {
                "5XX",
                "429",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest);
            };
            var retries = new Docusign.IAM.SDK.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode == 400 || _statusCode == 401 || _statusCode == 403 || _statusCode == 404 || _statusCode >= 400 && _statusCode < 500 || _statusCode == 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception error)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    WorkflowsListSuccess obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<WorkflowsListSuccess>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into WorkflowsListSuccess.", httpResponse, httpResponseBody, ex);
                    }

                    return obj!;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 403, 404}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 500)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 401 || responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

        public async Task<WorkflowTriggerRequirementsSuccess> GetWorkflowTriggerRequirementsAsync(string accountId, string workflowId, RetryConfig? retryConfig = null)
        {
            var request = new GetWorkflowTriggerRequirementsRequest()
            {
                AccountId = accountId,
                WorkflowId = workflowId,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/v1/accounts/{accountId}/workflows/{workflowId}/trigger-requirements", request);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "GetWorkflowTriggerRequirements", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            if (retryConfig == null)
            {
                if (this.SDKConfiguration.RetryConfig != null)
                {
                    retryConfig = this.SDKConfiguration.RetryConfig;
                }
                else
                {
                    var backoff = new BackoffStrategy(
                        initialIntervalMs: 500L,
                        maxIntervalMs: 5000L,
                        maxElapsedTimeMs: 30000L,
                        exponent: 1.5
                    );
                    retryConfig = new RetryConfig(
                        strategy: RetryConfig.RetryStrategy.BACKOFF,
                        backoff: backoff,
                        retryConnectionErrors: true
                    );
                }
            }

            List<string> statusCodes = new List<string>
            {
                "5XX",
                "429",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest);
            };
            var retries = new Docusign.IAM.SDK.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode == 400 || _statusCode == 401 || _statusCode == 403 || _statusCode == 404 || _statusCode >= 400 && _statusCode < 500 || _statusCode == 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception error)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    WorkflowTriggerRequirementsSuccess obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<WorkflowTriggerRequirementsSuccess>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into WorkflowTriggerRequirementsSuccess.", httpResponse, httpResponseBody, ex);
                    }

                    return obj!;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 403, 404}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 500)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 401 || responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

        public async Task<TriggerWorkflowSuccess> TriggerWorkflowAsync(string accountId, string workflowId, TriggerWorkflow triggerWorkflow, RetryConfig? retryConfig = null)
        {
            var request = new TriggerWorkflowRequest()
            {
                AccountId = accountId,
                WorkflowId = workflowId,
                TriggerWorkflow = triggerWorkflow,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/v1/accounts/{accountId}/workflows/{workflowId}/actions/trigger", request);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            var serializedBody = RequestBodySerializer.Serialize(request, "TriggerWorkflow", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "TriggerWorkflow", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            if (retryConfig == null)
            {
                if (this.SDKConfiguration.RetryConfig != null)
                {
                    retryConfig = this.SDKConfiguration.RetryConfig;
                }
                else
                {
                    var backoff = new BackoffStrategy(
                        initialIntervalMs: 500L,
                        maxIntervalMs: 5000L,
                        maxElapsedTimeMs: 30000L,
                        exponent: 1.5
                    );
                    retryConfig = new RetryConfig(
                        strategy: RetryConfig.RetryStrategy.BACKOFF,
                        backoff: backoff,
                        retryConnectionErrors: true
                    );
                }
            }

            List<string> statusCodes = new List<string>
            {
                "5XX",
                "429",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest);
            };
            var retries = new Docusign.IAM.SDK.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode == 400 || _statusCode == 401 || _statusCode == 403 || _statusCode == 404 || _statusCode >= 400 && _statusCode < 500 || _statusCode == 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception error)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    TriggerWorkflowSuccess obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<TriggerWorkflowSuccess>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into TriggerWorkflowSuccess.", httpResponse, httpResponseBody, ex);
                    }

                    return obj!;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 403, 404}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 500)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 401 || responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

        public async Task<PauseNewWorkflowInstancesSuccess> PauseNewWorkflowInstancesAsync(string accountId, string workflowId, RetryConfig? retryConfig = null)
        {
            var request = new PauseNewWorkflowInstancesRequest()
            {
                AccountId = accountId,
                WorkflowId = workflowId,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/v1/accounts/{accountId}/workflows/{workflowId}/actions/pause", request);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "pauseNewWorkflowInstances", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            if (retryConfig == null)
            {
                if (this.SDKConfiguration.RetryConfig != null)
                {
                    retryConfig = this.SDKConfiguration.RetryConfig;
                }
                else
                {
                    var backoff = new BackoffStrategy(
                        initialIntervalMs: 500L,
                        maxIntervalMs: 5000L,
                        maxElapsedTimeMs: 30000L,
                        exponent: 1.5
                    );
                    retryConfig = new RetryConfig(
                        strategy: RetryConfig.RetryStrategy.BACKOFF,
                        backoff: backoff,
                        retryConnectionErrors: true
                    );
                }
            }

            List<string> statusCodes = new List<string>
            {
                "5XX",
                "429",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest);
            };
            var retries = new Docusign.IAM.SDK.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode == 400 || _statusCode == 401 || _statusCode == 403 || _statusCode == 404 || _statusCode == 409 || _statusCode >= 400 && _statusCode < 500 || _statusCode == 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception error)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    PauseNewWorkflowInstancesSuccess obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<PauseNewWorkflowInstancesSuccess>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into PauseNewWorkflowInstancesSuccess.", httpResponse, httpResponseBody, ex);
                    }

                    return obj!;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 403, 404, 409}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 500)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 401 || responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

        public async Task<ResumeNewWorkflowInstancesSuccess> ResumePausedWorkflowAsync(string accountId, string workflowId, RetryConfig? retryConfig = null)
        {
            var request = new ResumePausedWorkflowRequest()
            {
                AccountId = accountId,
                WorkflowId = workflowId,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/v1/accounts/{accountId}/workflows/{workflowId}/actions/resume", request);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "resumePausedWorkflow", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            if (retryConfig == null)
            {
                if (this.SDKConfiguration.RetryConfig != null)
                {
                    retryConfig = this.SDKConfiguration.RetryConfig;
                }
                else
                {
                    var backoff = new BackoffStrategy(
                        initialIntervalMs: 500L,
                        maxIntervalMs: 5000L,
                        maxElapsedTimeMs: 30000L,
                        exponent: 1.5
                    );
                    retryConfig = new RetryConfig(
                        strategy: RetryConfig.RetryStrategy.BACKOFF,
                        backoff: backoff,
                        retryConnectionErrors: true
                    );
                }
            }

            List<string> statusCodes = new List<string>
            {
                "5XX",
                "429",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest);
            };
            var retries = new Docusign.IAM.SDK.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode == 400 || _statusCode == 401 || _statusCode == 403 || _statusCode == 404 || _statusCode == 409 || _statusCode >= 400 && _statusCode < 500 || _statusCode == 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception error)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ResumeNewWorkflowInstancesSuccess obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<ResumeNewWorkflowInstancesSuccess>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ResumeNewWorkflowInstancesSuccess.", httpResponse, httpResponseBody, ex);
                    }

                    return obj!;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 403, 404, 409}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 500)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorPayload.", httpResponse, httpResponseBody, ex);
                    }

                    throw new Error(payload, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 401 || responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }
    }
}