//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Hooks
{
    using System;
    using Newtonsoft.Json;

    /// <summary>
    /// Available scopes for the accessToken OAuth 2.0 scheme (authorizationCode flow).
    /// </summary>
    /// <remarks>
    /// JWT Bearer token from Docusign authorization server.
    /// </remarks>
    public enum AccessTokenOAuth2Scope
    {
        /// <summary>
        /// Allows read access to the unified repository.
        /// </summary>
        [JsonProperty("adm_store_unified_repo_read")]
        AdmStoreUnifiedRepoRead,

        /// <summary>
        /// Access to signature data.
        /// </summary>
        [JsonProperty("signature")]
        Signature,

        /// <summary>
        /// Allows management of advanced workflow operations.
        /// </summary>
        [JsonProperty("aow_manage")]
        AowManage,

        [JsonProperty("adm_store_unified_repo_write")]
        AdmStoreUnifiedRepoWrite,

        [JsonProperty("models_read")]
        ModelsRead,

        [JsonProperty("impersonation")]
        Impersonation,

        /// <summary>
        /// Read workspace profile information.
        /// </summary>
        [JsonProperty("dtr.company.read")]
        DtrCompanyRead,

        /// <summary>
        /// Read workspace data.
        /// </summary>
        [JsonProperty("dtr.rooms.read")]
        DtrRoomsRead,

        /// <summary>
        /// Update workspace data.
        /// </summary>
        [JsonProperty("dtr.rooms.write")]
        DtrRoomsWrite,

        /// <summary>
        /// Modify workspace documents.
        /// </summary>
        [JsonProperty("dtr.documents.write")]
        DtrDocumentsWrite,
    }


    public static class AccessTokenOAuth2ScopeExtension
    {
        public static string Value(this AccessTokenOAuth2Scope value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AccessTokenOAuth2Scope ToEnum(this string value)
        {
            foreach(var field in typeof(AccessTokenOAuth2Scope).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AccessTokenOAuth2Scope)
                    {
                        return (AccessTokenOAuth2Scope)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AccessTokenOAuth2Scope");
        }
    }
}
