//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Docusign.IAM.SDK.Models.Errors
{
    using System;
    using System.Net.Http;

    public class APIException : IamClientError
    {
        /// <summary>
        /// Default API exception.
        /// </summary>
        public APIException(
            string message,
            HttpResponseMessage rawResponse,
            string body
        ): base(message, rawResponse, body) {}
    }
}
