//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Errors
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;

    public class ErrorPayload
    {
        /// <summary>
        /// HTTP status code for the error.
        /// </summary>
        [JsonProperty("code")]
        public long? Code { get; set; }

        /// <summary>
        /// A message describing the error.
        /// </summary>
        [JsonProperty("error")]
        public string? ErrorValue { get; set; }

        /// <summary>
        /// The timestamp when the error occurred.
        /// </summary>
        [JsonProperty("timestamp")]
        public DateTime? Timestamp { get; set; }
    }

    /// <summary>
    /// Bad Request - The request could not be understood or was missing required parameters.
    /// </summary>
    public class Error : IamClientError
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public ErrorPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error.Payload.Code instead.")]
        public long? Code { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error.Payload.ErrorValue instead.")]
        public string? ErrorValue { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error.Payload.Timestamp instead.")]
        public DateTime? Timestamp { get; set; }

        public Error(
            ErrorPayload payload,
            HttpResponseMessage rawResponse,
            string body
        ): base("API error occurred", rawResponse, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Code = payload.Code;
           ErrorValue = payload.ErrorValue;
           Timestamp = payload.Timestamp;
           #pragma warning restore CS0618
        }
    }
}