//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Requests
{
    using Docusign.IAM.SDK.Utils;
    
    public class DeleteAgreementRequest
    {

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")]
        public string? AccountId { get; set; } = "00000000-0000-0000-0000-000000000000";

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=agreementId")]
        public string? AgreementId { get; set; } = "00000000-0000-0000-0000-000000000000";
    }
}