//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Requests
{
    using Docusign.IAM.SDK.Utils;
    
    public class GetAgreementsListRequest
    {

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")]
        public string? AccountId { get; set; } = "00000000-0000-0000-0000-000000000000";

        /// <summary>
        /// The maximum number of items that can be returned in a single page.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public int? Limit { get; set; } = null;

        /// <summary>
        /// An opaque token that helps retrieve the a page of data.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=ctoken")]
        public string? Ctoken { get; set; } = null;
    }
}