//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Requests
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The grant type. This value must be set to "refresh_token".
    /// </summary>
    public enum GetTokenFromRefreshTokenGrantType
    {
        [JsonProperty("refresh_token")]
        RefreshToken,
    }

    public static class GetTokenFromRefreshTokenGrantTypeExtension
    {
        public static string Value(this GetTokenFromRefreshTokenGrantType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetTokenFromRefreshTokenGrantType ToEnum(this string value)
        {
            foreach(var field in typeof(GetTokenFromRefreshTokenGrantType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetTokenFromRefreshTokenGrantType)
                    {
                        return (GetTokenFromRefreshTokenGrantType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetTokenFromRefreshTokenGrantType");
        }
    }
}