//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Requests
{
    using Docusign.IAM.SDK.Utils;
    
    public class GetWorkspaceBrandRequest
    {

        /// <summary>
        /// The ID of the account
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")]
        public string AccountId { get; set; } = default!;

        /// <summary>
        /// The ID of the workspace
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspaceId")]
        public string WorkspaceId { get; set; } = default!;
    }
}