//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Requests
{
    using Docusign.IAM.SDK.Models.Requests;
    using Docusign.IAM.SDK.Utils;

    public class GetWorkflowsListRequest
    {
        /// <summary>
        /// The unique identifier of the account.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")]
        public string AccountId { get; set; } = "00000000-0000-0000-0000-000000000000";

        /// <summary>
        /// Filter workflows by their status. If provided, only workflows with the specified status will be returned.<br/>
        /// - `active`: Returns only active workflows.<br/>
        /// - `inactive`: Returns only inactive workflows.<br/>
        /// - `publishing`: Returns workflows currently being published.<br/>
        /// - `unpublishing`: Returns workflows currently being unpublished.<br/>
        /// - `archived`: Returns workflows that have been archived.<br/>
        /// - `archiving`: Returns workflows currently being archived.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")]
        public Status? Status { get; set; }
    }
}