//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Requests
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Filter workflows by their status. If provided, only workflows with the specified status will be returned.<br/>
    /// 
    /// <remarks>
    /// - `active`: Returns only active workflows.<br/>
    /// - `inactive`: Returns only inactive workflows.<br/>
    /// - `publishing`: Returns workflows currently being published.<br/>
    /// - `unpublishing`: Returns workflows currently being unpublished.<br/>
    /// - `archived`: Returns workflows that have been archived.<br/>
    /// - `archiving`: Returns workflows currently being archived.        <br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum Status
    {
        [JsonProperty("active")]
        Active,
        [JsonProperty("inactive")]
        Inactive,
        [JsonProperty("publishing")]
        Publishing,
        [JsonProperty("unpublishing")]
        Unpublishing,
        [JsonProperty("archived")]
        Archived,
        [JsonProperty("archiving")]
        Archiving,
    }

    public static class StatusExtension
    {
        public static string Value(this Status value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Status ToEnum(this string value)
        {
            foreach(var field in typeof(Status).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Status)
                    {
                        return (Status)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Status");
        }
    }

}