//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;

    public class AddWorkspaceDocumentRequest
    {
        /// <summary>
        /// The file within the multipart/form-data.
        /// </summary>
        [SpeakeasyMetadata("multipartForm:file,name=file")]
        public AddWorkspaceDocumentRequestFile? File { get; set; }
    }
}