//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Link to the collection of configured agreement types for the account. Always present.
    /// </summary>
    public class AgreementLinksAgreementTypes
    {
        /// <summary>
        /// The URL for the referenced page.
        /// </summary>
        [JsonProperty("href")]
        public string Href { get; set; } = default!;
    }
}