//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Available actions on the agreement. Actions are conditionally present based on the current state of the resource.
    /// </summary>
    public class AgreementActions
    {
        /// <summary>
        /// Change the agreement type to a different configured type.<br/>
        /// Only present when the agreement type is mutable.
        /// </summary>
        [JsonProperty("change_type")]
        public AgreementActionsChangeType? ChangeType { get; set; }
    }
}