//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Hypermedia controls (HATEOAS) for agreement specific links to resources.
    /// </summary>
    public class AgreementLinks
    {
        /// <summary>
        /// A URL that references a specific resource.
        /// </summary>
        [JsonProperty("document")]
        public Link? Document { get; set; } = null;
    }
}