//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    public class BrandLogos
    {
        [JsonProperty("primary")]
        public string? Primary { get; set; } = null;

        [JsonProperty("secondary")]
        public string? Secondary { get; set; } = null;

        [JsonProperty("email")]
        public string? Email { get; set; } = null;
    }
}