//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    public class BulkJobItemActions
    {
        /// <summary>
        /// Azure Blob Store presigned URL to upload the document file (valid for ~8 hours).
        /// </summary>
        [JsonProperty("upload_document")]
        public string? UploadDocument { get; set; }

        /// <summary>
        /// Azure Blob Store url to upload metadata of the specific file.
        /// </summary>
        [JsonProperty("upload_metadata")]
        public string? UploadMetadata { get; set; }
    }
}