//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Properties about THIS request/response, not the job resource itself.
    /// </summary>
    public class BulkJobMetadata
    {
        [JsonProperty("request_id")]
        public string? RequestId { get; set; }

        /// <summary>
        /// Time in ms to process this request.
        /// </summary>
        [JsonProperty("response_duration")]
        public int? ResponseDuration { get; set; }

        /// <summary>
        /// When this response was generated.
        /// </summary>
        [JsonProperty("response_timestamp")]
        public DateTime? ResponseTimestamp { get; set; }
    }
}