//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Job lifecycle states:<br/>
    /// * OPEN - Job created and accepting documents<br/>
    /// * UPLOAD_COMPLETE - All documents have been received, and processing has not yet started<br/>
    /// * IN_PROGRESS - Documents are being processed (AI extraction)<br/>
    /// * COMPLETE - The full e2e process is complete<br/>
    /// * FAILED - System error prevented job execution<br/>
    /// * CANCELED - User initiated request to cancel a job.
    /// </summary>
    public enum BulkJobStatus
    {
        [JsonProperty("OPEN")]
        Open,
        [JsonProperty("UPLOAD_COMPLETE")]
        UploadComplete,
        [JsonProperty("IN_PROGRESS")]
        InProgress,
        [JsonProperty("COMPLETE")]
        Complete,
        [JsonProperty("FAILED")]
        Failed,
        [JsonProperty("CANCELLED")]
        Cancelled,
    }

    public static class BulkJobStatusExtension
    {
        public static string Value(this BulkJobStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static BulkJobStatus ToEnum(this string value)
        {
            foreach(var field in typeof(BulkJobStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is BulkJobStatus)
                    {
                        return (BulkJobStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum BulkJobStatus");
        }
    }
}