//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    public class BulkJobEmbeddedItems
    {
        [JsonProperty("_actions")]
        public BulkJobItemActions? Actions { get; set; }

        /// <summary>
        /// Agreement ID associated with this document, if created.
        /// </summary>
        [JsonProperty("agreement_id")]
        public string? AgreementId { get; set; }

        /// <summary>
        /// Error message if document processing failed.
        /// </summary>
        [JsonProperty("error")]
        public string? Error { get; set; }

        /// <summary>
        /// Error code if document processing failed.
        /// </summary>
        [JsonProperty("error_code")]
        public int? ErrorCode { get; set; }

        /// <summary>
        /// Id of the document.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Sequential order of the document.
        /// </summary>
        [JsonProperty("sequence")]
        public int? Sequence { get; set; }

        /// <summary>
        /// Document status. Last 3 are terminal statuses. Matches enum with similar name in the backend.
        /// </summary>
        [JsonProperty("status")]
        public DocStatus? Status { get; set; }
    }
}