//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    
    public class CreateWorkspaceBody
    {

        /// <summary>
        /// The name of the workspace
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Include)]
        public string? Name { get; set; }

        /// <summary>
        /// A GUID value that identifies a brand. For more information, see &lt;a href=&quot;https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/&quot;&gt;Branding&lt;/a&gt;
        /// </summary>
        [JsonProperty("brand_id")]
        public string? BrandId { get; set; } = null;
    }
}