//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    
    public class CreateWorkspaceDocumentOwner
    {

        [JsonProperty("user_id")]
        public string? UserId { get; set; } = null;

        [JsonProperty("first_name")]
        public string? FirstName { get; set; } = null;

        [JsonProperty("last_name")]
        public string? LastName { get; set; } = null;
    }
}