//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class DefaultValueType
    {
        private DefaultValueType(string value) { Value = value; }

        public string Value { get; private set; }

        public static DefaultValueType Str { get { return new DefaultValueType("str"); } }

        public static DefaultValueType Number { get { return new DefaultValueType("number"); } }

        public static DefaultValueType Boolean { get { return new DefaultValueType("boolean"); } }

        public static DefaultValueType MapOfAny { get { return new DefaultValueType("mapOfAny"); } }

        public static DefaultValueType ArrayOfAny { get { return new DefaultValueType("arrayOfAny"); } }

        public static DefaultValueType Null { get { return new DefaultValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(DefaultValueType v) { return v.Value; }
        public static DefaultValueType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "mapOfAny": return MapOfAny;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for DefaultValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((DefaultValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The default value for the input field if one is provided. This can be a string, number,<br/>
    /// 
    /// <remarks>
    /// boolean, object, or array. If no value is provided during the trigger, the workflow may<br/>
    /// use this default value.<br/>
    /// 
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(DefaultValue.DefaultValueConverter))]
    public class DefaultValue
    {
        public DefaultValue(DefaultValueType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public DefaultValueType Type { get; set; }
        public static DefaultValue CreateStr(string str)
        {
            DefaultValueType typ = DefaultValueType.Str;

            DefaultValue res = new DefaultValue(typ);
            res.Str = str;
            return res;
        }
        public static DefaultValue CreateNumber(double number)
        {
            DefaultValueType typ = DefaultValueType.Number;

            DefaultValue res = new DefaultValue(typ);
            res.Number = number;
            return res;
        }
        public static DefaultValue CreateBoolean(bool boolean)
        {
            DefaultValueType typ = DefaultValueType.Boolean;

            DefaultValue res = new DefaultValue(typ);
            res.Boolean = boolean;
            return res;
        }
        public static DefaultValue CreateMapOfAny(Dictionary<string, object> mapOfAny)
        {
            DefaultValueType typ = DefaultValueType.MapOfAny;

            DefaultValue res = new DefaultValue(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }
        public static DefaultValue CreateArrayOfAny(List<object> arrayOfAny)
        {
            DefaultValueType typ = DefaultValueType.ArrayOfAny;

            DefaultValue res = new DefaultValue(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static DefaultValue CreateNull()
        {
            DefaultValueType typ = DefaultValueType.Null;
            return new DefaultValue(typ);
        }

        public class DefaultValueConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(DefaultValue);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"'){
                    return new DefaultValue(DefaultValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new DefaultValue(DefaultValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new DefaultValue(DefaultValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new DefaultValue(DefaultValueType.MapOfAny)
                    {
                        MapOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, object>), new DefaultValue(DefaultValueType.MapOfAny), "MapOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new DefaultValue(DefaultValueType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new DefaultValue(DefaultValueType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                DefaultValue res = (DefaultValue)value;
                if (DefaultValueType.FromString(res.Type).Equals(DefaultValueType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfAny));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}