//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Link to download the document.
    /// </summary>
    public class Document
    {
        /// <summary>
        /// URL to download the document.
        /// </summary>
        [JsonProperty("href")]
        public string? Href { get; set; }
    }
}