//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    
    /// <summary>
    /// The data type expected for the input field. This indicates whether the input should<br/>
    /// 
    /// <remarks>
    /// be a string, number, boolean, object, or array, ensuring the data is passed in the<br/>
    /// correct format.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public class FieldDataType
    {
    }
}