//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class GetWorkspaceEnvelopesResponse
    {

        /// <summary>
        /// The summary list of envelopes associated with the workspace
        /// </summary>
        [JsonProperty("envelopes", NullValueHandling = NullValueHandling.Include)]
        public List<WorkspaceEnvelopeSummary>? Envelopes { get; set; }
    }
}