//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// The details of a single workspace
    /// </summary>
    public class GetWorkspaceResponse
    {

        /// <summary>
        /// The ID of the workspace
        /// </summary>
        [JsonProperty("workspace_id")]
        public string WorkspaceId { get; set; } = default!;

        /// <summary>
        /// The name of the workspace
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        /// <summary>
        /// The date the workspace was created
        /// </summary>
        [JsonProperty("created_date")]
        public DateTime? CreatedDate { get; set; } = null;

        /// <summary>
        /// The ID of the user who created the workspace
        /// </summary>
        [JsonProperty("created_by_user_id")]
        public string? CreatedByUserId { get; set; } = null;

        /// <summary>
        /// The list of user IDs of the workspace owners
        /// </summary>
        [JsonProperty("workspace_owner_ids")]
        public List<string>? WorkspaceOwnerIds { get; set; } = null;
    }
}