//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class GetWorkspaceUsersResponse
    {

        /// <summary>
        /// The user summary list. Includes the ID, name, and metadata such as the role ID and role name
        /// </summary>
        [JsonProperty("users", NullValueHandling = NullValueHandling.Include)]
        public List<WorkspaceUserSummary>? Users { get; set; }

        /// <summary>
        /// The number of users returned in the response. Always equal or less than the `count` of the request
        /// </summary>
        [JsonProperty("result_set_size")]
        public int? ResultSetSize { get; set; } = null;

        /// <summary>
        /// Position of the first item in the total results
        /// </summary>
        [JsonProperty("start_position")]
        public int? StartPosition { get; set; } = null;

        /// <summary>
        /// Position of the last item in the total results
        /// </summary>
        [JsonProperty("end_position")]
        public int? EndPosition { get; set; } = null;

        /// <summary>
        /// The total number of users in the workspace applicable to the request regardless of pagination. It may not always be computed
        /// </summary>
        [JsonProperty("total_row_count")]
        public int? TotalRowCount { get; set; } = null;
    }
}