//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Identifies records in external systems which correlate with this agreement.
    /// </summary>
    public class LinkedData
    {
        [JsonProperty("application_name")]
        public string? ApplicationName { get; set; }

        [JsonProperty("object_name")]
        public string? ObjectName { get; set; }

        [JsonProperty("record_id")]
        public string? RecordId { get; set; }
    }
}