//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The HTTP method used to trigger the workflow. This defines the type of request<br/>
    /// that will initiate the workflow (e.g., GET, POST).
    /// </summary>
    public enum Method
    {
        [JsonProperty("GET")]
        Get,
        [JsonProperty("POST")]
        Post,
        [JsonProperty("PUT")]
        Put,
        [JsonProperty("PATCH")]
        Patch,
        [JsonProperty("DELETE")]
        Delete,
    }

    public static class MethodExtension
    {
        public static string Value(this Method value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Method ToEnum(this string value)
        {
            foreach(var field in typeof(Method).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Method)
                    {
                        return (Method)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Method");
        }
    }
}