//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Control information and metadata for the response.
    /// </summary>
    public class ResponseMetadata
    {

        /// <summary>
        /// The maximum number of items that can be returned in a single page.
        /// </summary>
        [JsonProperty("page_limit")]
        public int? PageLimit { get; set; } = null;

        /// <summary>
        /// The continuation token used to retrieve a page in a paginated response.
        /// </summary>
        [JsonProperty("page_token_next")]
        public string? PageTokenNext { get; set; } = null;

        /// <summary>
        /// Unique identifier for the request, useful for tracking and debugging.
        /// </summary>
        [JsonProperty("request_id", NullValueHandling = NullValueHandling.Include)]
        public string? RequestId { get; set; }

        /// <summary>
        /// The timestamp indicating when the response was generated.
        /// </summary>
        [JsonProperty("response_timestamp", NullValueHandling = NullValueHandling.Include)]
        public DateTime? ResponseTimestamp { get; set; }

        /// <summary>
        /// The duration of time, in milliseconds, that the server took to process and respond <br/>
        /// 
        /// <remarks>
        /// to the request. This is measured from the time the server received the request <br/>
        /// until the time the response was sent.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("response_duration_ms", NullValueHandling = NullValueHandling.Include)]
        public int? ResponseDurationMs { get; set; }
    }
}