//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The operation that the field supports.
    /// </summary>
    public enum SupportedOperation
    {
        [JsonProperty("VerifyType")]
        VerifyType,
    }

    public static class SupportedOperationExtension
    {
        public static string Value(this SupportedOperation value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SupportedOperation ToEnum(this string value)
        {
            foreach(var field in typeof(SupportedOperation).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SupportedOperation)
                    {
                        return (SupportedOperation)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SupportedOperation");
        }
    }
}