//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    public class TabConnectionInstance
    {
        /// <summary>
        /// Identifies an extension app's unique connection key.
        /// </summary>
        [JsonProperty("connectionKey")]
        public string ConnectionKey { get; set; } = default!;

        /// <summary>
        /// Identifies an extension app's connection instance.
        /// </summary>
        [JsonProperty("connectionValue")]
        public string ConnectionValue { get; set; } = default!;
    }
}