//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Models.Components;
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Array of fields required as inputs to trigger the workflow, including field names, data types, and default values.
    /// </summary>
    public class TriggerInputSchema
    {
        /// <summary>
        /// The name of the input field expected by the workflow. This key must match the name<br/>
        /// provided in the `trigger_inputs` when triggering the workflow.
        /// </summary>
        [JsonProperty("field_name")]
        public string? FieldName { get; set; }

        /// <summary>
        /// The data type expected for the input field. This indicates whether the input should<br/>
        /// be a string, number, boolean, object, or array, ensuring the data is passed in the<br/>
        /// correct format.
        /// </summary>
        [JsonProperty("field_data_type")]
        public string? FieldDataType { get; set; }

        /// <summary>
        /// The default value for the input field if one is provided. This can be a string, number,<br/>
        /// boolean, object, or array. If no value is provided during the trigger, the workflow may<br/>
        /// use this default value.
        /// </summary>
        [JsonProperty("default_value", NullValueHandling = NullValueHandling.Include)]
        public DefaultValue? DefaultValue { get; set; }
    }
}