//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Docusign.IAM.SDK.Models.Components
{
    using Docusign.IAM.SDK.Utils;
    using Newtonsoft.Json;
    
    public class UpdateWorkspaceUserResponse
    {

        /// <summary>
        /// The ID of the role assigned to the user
        /// </summary>
        [JsonProperty("role_id")]
        public string? RoleId { get; set; }
    }
}